/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraficaBarras.java
 *
 * Created on 03-oct-2013, 10:46:28
 */
package Servidor;


import Cliente.Candidato;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class GraficaBarras extends javax.swing.JFrame {
    private GraficadorBarras graficadorBarras = new GraficadorBarras();
    private String informacion;
    /**
     * Creates new form GraficaBarras
     */
    public GraficaBarras() {
        initComponents();
        
        desplegar();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGrafica = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoInformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelGraficaLayout = new javax.swing.GroupLayout(PanelGrafica);
        PanelGrafica.setLayout(PanelGraficaLayout);
        PanelGraficaLayout.setHorizontalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addComponent(etiquetaNombre)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        PanelGraficaLayout.setVerticalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addComponent(etiquetaNombre)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        areaTextoInformacion.setColumns(20);
        areaTextoInformacion.setRows(5);
        jScrollPane1.setViewportView(areaTextoInformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGrafica;
    private javax.swing.JTextArea areaTextoInformacion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    public void actualizar(Object objeto) {
        ArrayList<Candidato> candidatos = ((ArrayList<Candidato>)objeto);
        informacion = "";
        for (int contador = 0; contador < candidatos.size(); contador++) {
            Dato dato = new Dato(candidatos.get(contador).getNombre(), candidatos.get(contador).getCantidadDeVotos());
            graficadorBarras.añadirDato(dato);
            informacion = informacion + "\n" + candidatos.get(contador).getNombre() + " tiene " + candidatos.get(contador).getCantidadDeVotos(); 
        }
        
        desplegar();
    }

    private void desplegar() {
        areaTextoInformacion.setText(informacion);
        graficadorBarras.graficar("Votaciones 2013");
        etiquetaNombre.setSize(PanelGrafica.getSize());
        etiquetaNombre.setIcon(new ImageIcon(graficadorBarras.darGrafica()));
        etiquetaNombre.updateUI();

    }
}
